language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t wyyazty123/docker-react -f Dockerfile.dev .



script:
  - docker run -e CI=true wyyazty123/docker-react npm run test